# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(2880, 988)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        font.setPointSize(10)
        font.setItalic(True)
        MainWindow.setFont(font)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("plot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(400, 10, 661, 791))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_dikiful = QtWidgets.QLabel(self.centralwidget)
        self.label_dikiful.setGeometry(QtCore.QRect(1070, 40, 491, 21))
        self.label_dikiful.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_dikiful.setText("")
        self.label_dikiful.setObjectName("label_dikiful")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(1070, 140, 491, 291))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 220, 371, 362))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.sdiffcheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.sdiffcheckBox.setObjectName("sdiffcheckBox")
        self.gridLayout_2.addWidget(self.sdiffcheckBox, 1, 0, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.dispcheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.dispcheckBox.setObjectName("dispcheckBox")
        self.gridLayout_2.addWidget(self.dispcheckBox, 3, 0, 1, 1)
        self.sdiffspinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sdiffspinBox.setMinimum(1)
        self.sdiffspinBox.setObjectName("sdiffspinBox")
        self.gridLayout_2.addWidget(self.sdiffspinBox, 1, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.radioButton_ar = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_ar.setObjectName("radioButton_ar")
        self.verticalLayout.addWidget(self.radioButton_ar)
        self.radioButton_arima = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_arima.setObjectName("radioButton_arima")
        self.verticalLayout.addWidget(self.radioButton_arima)
        self.radioButton_arch = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_arch.setObjectName("radioButton_arch")
        self.verticalLayout.addWidget(self.radioButton_arch)
        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout.addWidget(self.radioButton)
        self.checkBox_forecast = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_forecast.setObjectName("checkBox_forecast")
        self.verticalLayout.addWidget(self.checkBox_forecast)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.sdiffspinBox_2 = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sdiffspinBox_2.setWrapping(False)
        self.sdiffspinBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sdiffspinBox_2.setMinimum(1)
        self.sdiffspinBox_2.setMaximum(45)
        self.sdiffspinBox_2.setObjectName("sdiffspinBox_2")
        self.verticalLayout.addWidget(self.sdiffspinBox_2)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.gridLayout_2.addLayout(self.verticalLayout, 6, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 371, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.dateEdit_2 = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2004, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.gridLayout_5.addWidget(self.dateEdit_2, 6, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 2, 1, 1, 1)
        self.dateEdit = QtWidgets.QDateEdit(self.verticalLayoutWidget)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout_5.addWidget(self.dateEdit, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 6, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 4, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_5)
        self.label_dikiful_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_dikiful_2.setGeometry(QtCore.QRect(1070, 70, 491, 21))
        self.label_dikiful_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_dikiful_2.setText("")
        self.label_dikiful_2.setObjectName("label_dikiful_2")
        self.gridLayoutWidget_7 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_7.setGeometry(QtCore.QRect(1070, 430, 491, 291))
        self.gridLayoutWidget_7.setObjectName("gridLayoutWidget_7")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_7)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.tableView = QtWidgets.QTableView(self.gridLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Georgia")
        self.tableView.setFont(font)
        self.tableView.setObjectName("tableView")
        self.gridLayout_7.addWidget(self.tableView, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(1080, 110, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(1070, 10, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Financial Time Series Analyzer"))
        self.sdiffcheckBox.setText(_translate("MainWindow", "Дифференцирование"))
        self.checkBox.setText(_translate("MainWindow", "Логарифм доходности"))
        self.dispcheckBox.setText(_translate("MainWindow", "Стабилизировать дисперсию"))
        self.label_4.setText(_translate("MainWindow", "Построить модель"))
        self.radioButton_ar.setText(_translate("MainWindow", "AR"))
        self.radioButton_arima.setText(_translate("MainWindow", "ARIMA"))
        self.radioButton_arch.setText(_translate("MainWindow", "ARCH"))
        self.radioButton.setText(_translate("MainWindow", "Не строить"))
        self.checkBox_forecast.setText(_translate("MainWindow", "Постоить прогноз"))
        self.label_5.setText(_translate("MainWindow", "Горизонт прогнозирвоания"))
        self.pushButton.setText(_translate("MainWindow", "Анализировать"))
        self.label_7.setText(_translate("MainWindow", "Параметры"))
        self.label_8.setText(_translate("MainWindow", "Данные"))
        self.label_9.setText(_translate("MainWindow", "Введите тиккер актива, который хотите проанализировать. Например AAPL. INTC, NKE"))
        self.label.setText(_translate("MainWindow", "Код актива"))
        self.label_3.setText(_translate("MainWindow", "По"))
        self.label_2.setText(_translate("MainWindow", "С"))
        self.label_10.setText(_translate("MainWindow", "Прогноз"))
        self.label_11.setText(_translate("MainWindow", "Статистики"))

